project:
  type: website

website:
  title: "Applied LLMs"
  image: images/hamel_cover_img.png
  favicon: favicon.ico
  google-analytics: "G-TL6F6S3QZP"
  twitter-card: true
  margin-footer: |
    <div class="margin-subscribe">
      <p>Join 300+ readers getting updates on how to apply LLMs effectively</p>
      <script async data-uid="b3e2fda9e7" src="https://appliedllms.ck.page/b3e2fda9e7/index.js"></script>
    </div>
    <style>
      .margin-subscribe {
        border: none;
        /* Same color as header */
        background-color: #375a7f;
        padding: 0.5em 0.5em 0 0.5em;
        border-radius: 5px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }
      .margin-subscribe p {
        margin-bottom: 0;
        font-size: 0.9em;
        text-align: center;
        color: white;
      }
    </style>
  open-graph: true
  navbar:
    left:
      - text: Courses
        file: courses.qmd
      - text: Services
        file: services.qmd
      - text: Job Board
        href: https://jobs.applied-llms.org/ 
      - text: Team
        file: about.qmd
  repo-url: https://github.com/parlance-labs/applied-llms
  site-url: https://applied-llms.org

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
