project:
  type: website

website:
  title: "Applied LLMs"
  image: images/mkdocs_social_card.png
  twitter-card: true
  margin-footer: |
    <script async data-uid="b3e2fda9e7" src="https://appliedllms.ck.page/b3e2fda9e7/index.js"></script>
  # <center id="toc-title">Subscribe</center>
  # <div class="margin-subscribe">
  # <script async data-uid="b3e2fda9e7" src="https://appliedllms.ck.page/b3e2fda9e7/index.js"></script>
  # </div>
  open-graph: true
  navbar:
    left:
      - text: About The Authors
        file: about.qmd
  repo-url: https://github.com/parlance-labs/applied-llms
  site-url: https://applied-llms.org

format:
  html:
    linkcolor: blue
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
