project:
  type: website

website:
  title: "Applied LLMs"
  image: images/hamel_cover_img.png
  favicon: favicon.ico
  google-analytics: "G-TL6F6S3QZP"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - text: Courses
        file: courses.qmd
      - text: Services
        file: services.qmd
      - text: Job Board
        href: https://applied-llms.org/jobs
      - text: Team
        file: about.qmd
  repo-url: https://github.com/parlance-labs/applied-llms
  site-url: https://applied-llms.org

format:
  html:
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
